
name: pak build, macOS-latest, R 3.6

on:
  workflow_dispatch:
  push:

jobs:
  pak:
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
    - uses: actions/checkout@v1
    - uses: r-hub/actions/pak-builder@feature/pak-builder
      with:
        rversions: "3.6"
