
name: Build pak binary

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS (ubuntu-latest, macOS-latest, windows-2016)'
        required: true
        default: 'ubuntu-latest'
      rversions:
        description: 'R versions (e.g. "4.0, devel/4.1")'
        required: true
        default: '4.0'
  repository_dispatch:
    types: [pak-build]

jobs:
  pak:
    runs-on: ${{ github.event.client_payload.os }}${{ github.event.inputs.os }}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
    - uses: actions/checkout@v1
    - uses: r-hub/actions/pak-builder@feature/pak-builder
      with:
        rversions: ${{ github.event.client_payload.rversions }}${{ github.event.inputs.rversions }}
