
name: Trigger pak builds

on:
  workflow_dispatch:

jobs:
  dispatch:
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: '4.0' }
          - {os: macOS-latest,  r: '4.0' }
          - {os: windows-2016,  r: '4.0' }

    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: r-lib/pak
          event-type: pak-build
          client-payload: '{"os":"${{matrix.os}}","rversions":"${{matrix.r}}"}'
