
name: Build pak binary

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS (ubuntu-latest, macOS-latest, windows-2016)'
        required: true
        default: 'ubuntu-latest'
      rversions:
        description: 'R versions (e.g. "4.0, devel/4.1")'
        required: true
        default: '4.0'
  repository_dispatch:
    types: [pak-build]

jobs:
  pak:
    name: "pak build on R ${{ github.event.client_payload.rversions }}${{ github.event.inputs.rversions }}, ${{ github.event.client_payload.os }}${{ github.event.inputs.os }}"
    runs-on: ${{ github.event.client_payload.os }}${{ github.event.inputs.os }}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Job information
        run: |
          echo "OS: ${{ github.event.client_payload.os }}${{ github.event.inputs.os }}"
          echo "R versions: ${{ github.event.client_payload.rversions }}${{ github.event.inputs.rversions }}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: pak build
        uses: r-hub/actions/pak-builder@feature/pak-builder
        with:
          rversions: ${{ github.event.client_payload.rversions }}${{ github.event.inputs.rversions }}

      - name: Wait for publishing
        uses: r-lib/turnstyle@v1
        with:
          same-branch-only: false
        env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Publish
        uses: r-hub/actions/pak-publisher@feature/pak-builder
        with:
          token: ${{ secrets.TOKEN }}
          rversions: ${{ github.event.client_payload.rversions }}${{ github.event.inputs.rversions }}
