name: Nighly build

on:
  workflow_dispatch:
  push:
    branches:
    - 'feature/build-macos'
  schedule:
  - cron: '30 5 * * *'

# =========================================================================

jobs:

  # -----------------------------------------------------------------------
  macos:
    runs-on: macos-11
    if: false
    name: macOS x86_64 pak binaries
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Install rim
      run: |
        curl -OL https://github.com/gaborcsardi/rim/releases/download/v0.1.4/rim-0.1.4-macOS-x86_64.pkg
        sudo installer -pkg rim-0.1.4-macOS-x86_64.pkg -target /

    - name: Install R
      run: |
        sudo rim add 3.4
        sudo rim add 3.5
        sudo rim add 3.6
        sudo rim add 4.0
        sudo rim add 4.1
        sudo rim add devel

    - name: Install skopeo
      run: |
        brew install skopeo

    - name: Build pak binaries
      run: |
        cd tools/build/macos && make build

    - name: Run tests
      run: |
        cd tools/build/macos && make test

    - name: Deploy packages
      run: |
        cd tools/build/macos && make deploy
      env:
        PAK_GHCR_TOKEN: ${{ secrets.PAK_GHCR_TOKEN }}
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

  # -----------------------------------------------------------------------
  windows:
    runs-on: windows-latest
    if: false
    name: Windows pak binaries
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Build pak binaries
      uses: r-hub/actions/pak-builder@master
      with:
        token: ${{ secrets.TOKEN }}
        rversions: 3.4,3.5,3.6,4.0,4.1,devel/4.2

  # -----------------------------------------------------------------------
  linux:
    runs-on: ubuntu-18.04
    name: Linux static x86_64 pak binary for R ${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: '4.2' }
          - { r: '4.1' }
          - { r: '4.0' }
          - { r: '3.6' }
          - { r: '3.5' }
          - { r: '3.4' }

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: tools/build/linux/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        build-args: |
          R_MAJOR=${{ matrix.config.r }}
          TOKEN=${{ secrets.PAK_GHCR_TOKEN }}
