name: Daily pak build

on:
  schedule:
    - cron:  '55 6 * * *'

name: pak-builder

jobs:
  pak:
    runs-on: macOS-latest
    steps:
     - uses: actions/checkout@v1
     - uses: r-hub/actions/pak-builder@feature/pak-builder
       with:
         token: ${{ secrets.TOKEN }}
